name = "robobub-actions"
main = "src/index.ts"
compatibility_date = "2023-08-20"

[vars]

[env.production]
vars = { ENVIRONMENT = "production" }
routes = [
  { pattern = "robobub.luxass.dev", custom_domain = true },
  { pattern = "robobub.luxass.com", custom_domain = true }
]

[triggers]
crons = [ "*/1 * * * *" ]
