name: deploy to production

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a deployment
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main

# remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'robobub/actions'
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - name: setup node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: lts/*

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build

      - name: lint
        run: pnpm run lint

      - name: typecheck
        run: pnpm run typecheck

      - name: test
        run: pnpm run test

      - name: deploy
        id: deploy
        if: ${{ github.event.inputs.dry-run != 'true' }}
        uses: cloudflare/wrangler-action@9acf94ace14e7dc412b076f2c5c20b8ce93c79cd # v3.15.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: .
          environment: production
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
